import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Memories- Do not Open </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Made with 💖 by
            <code className={styles.code}> Riya , Sakshi and Aryan</code>
          </p>
          <div>
            <a
              href="https://github.com/kiritocode1/Memories"
              target="_blank"
              rel="noopener noreferrer"
              className={"text-slate-500"}
            >
              MEMORIES v.0.1 / code
            </a>
          </div>
        </div>

        <div className={ styles.center }>
          <h1>Memories - Ai Powered mental health helper </h1>
        </div>

      </main>
    </>
  )
}
