import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import CreditsCard from '@/Components/CreditsCard'
import GithubCard from '@/Components/GithubCard'
import MainPart from "@/Components/MainPart"; 
import ExplainCard from '@/Components/ExplainCard'
 
const inter = Inter({ subsets: [ 'latin' ] })



export default function Home() {

  return (
    <>
      <Head>
        <title>Memories- Do not Open </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col justify-center items-center p-[6rem] bg-black text-white min-h-[100vh]">
        <div className="flex  items-center  justify-around gap-20  w-full flex-wrap">
          <CreditsCard />
          <GithubCard/>
        </div>

        <div className={ styles.center }>
          <h1>Memories - Ai Powered mental health helper </h1>
        </div>
        
        <MainPart />
        <ExplainCard/>
      </main>
    </>
  )
}
